export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'

export const COMMENT_DETAILS_REQUEST = 'COMMENT_DETAILS_REQUEST'
export const COMMENT_DETAILS_SUCCESS = 'COMMENT_DETAILS_SUCCESS'
export const COMMENT_DETAILS_FAIL = 'COMMENT_DETAILS_FAIL'

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL'

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL'
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET'

export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST'
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS'
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL'
export const COMMENT_UPDATE_RESET = 'COMMENT_UPDATE_RESET'

export const COMMENT_CREATE_REVIEW_REQUEST = 'COMMENT_CREATE_REVIEW_REQUEST'
export const COMMENT_CREATE_REVIEW_SUCCESS = 'COMMENT_CREATE_REVIEW_SUCCESS'
export const COMMENT_CREATE_REVIEW_FAIL = 'COMMENT_CREATE_REVIEW_FAIL'
export const COMMENT_CREATE_REVIEW_RESET = 'COMMENT_CREATE_REVIEW_RESET'

export const COMMENT_TOP_REQUEST = 'COMMENT_TOP_REQUEST'
export const COMMENT_TOP_SUCCESS = 'COMMENT_TOP_SUCCESS'
export const COMMENT_TOP_FAIL = 'COMMENT_TOP_FAIL'
