export const REQUEST_CREATE_SUBSCRIBER = 'REQUEST_CREATE_SUBSCRIBER'
export const SUCCESS_CREATE_SUBSCRIBER = 'SUCCESS_CREATE_SUBSCRIBER'
export const FAIL_CREATE_SUBSCRIBER = 'FAIL_CREATE_SUBSCRIBER'
export const RESET_CREATE_SUBSCRIBER = 'RESET_CREATE_SUBSCRIBER'

export const REQUEST_READ_SUBSCRIBERS = 'REQUEST_READ_SUBSCRIBERS'
export const SUCCESS_READ_SUBSCRIBERS = 'SUCCESS_READ_SUBSCRIBERS'
export const FAIL_READ_SUBSCRIBERS = 'FAIL_READ_SUBSCRIBERS'
export const RESET_READ_SUBSCRIBERS = 'RESET_READ_SUBSCRIBERS'

export const SUBSCRIBER_DELETE_REQUEST = 'SUBSCRIBER_DELETE_REQUEST'
export const SUBSCRIBER_DELETE_SUCCESS = 'SUBSCRIBER_DELETE_SUCCESS'
export const SUBSCRIBER_DELETE_FAIL = 'SUBSCRIBER_DELETE_FAIL'