export const REQUEST_CREATE_TAGS = 'REQUEST_CREATE_TAGS'
export const SUCCESS_CREATE_TAGS = 'SUCCESS_CREATE_TAGS'
export const FAIL_CREATE_TAGS = 'FAIL_CREATE_TAGS'
export const RESET_CREATE_TAGS = 'RESET_CREATE_TAGS'

export const REQUEST_READ_TAGS = 'REQUEST_READ_TAGS'
export const SUCCESS_READ_TAGS = 'SUCCESS_READ_TAGS'
export const FAIL_READ_TAGS = 'FAIL_READ_TAGS'


export const REQUEST_UPDATE_TAGS = 'REQUEST_UPDATE_TAGS'
export const SUCCESS_UPDATE_TAGS = 'SUCCESS_UPDATE_TAGS'
export const FAIL_UPDATE_TAGS = 'FAIL_UPDATE_TAGS'
export const RESET_UPDATE_TAGS = 'RESET_UPDATE_TAGS'

export const TAG_DELETE_REQUEST = 'TAG_DELETE_REQUEST'
export const TAG_DELETE_SUCCESS = 'TAG_DELETE_SUCCESS'
export const TAG_DELETE_FAIL = 'TAG_DELETE_FAIL'

export const TAG_DETAILS_REQUEST ='TAG_DETAILS_REQUEST'
export const TAG_DETAILS_SUCCESS ='TAG_DETAILS_SUCCESS'
export const TAG_DETAILS_FAIL ='TAG_DETAILS_FAIL'
